[package]
name = "servente"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
httpdate = "*"
lazy_static = "*"
rcgen = "*"
rstest = "*"
rustls = { version = "*", features = ["quic"] }
rustls-pemfile = "*"
stretto = { version = "*", features = ["async"] }
tokio = { version = "*", features = ["full"] }
tokio-rustls = "*"
phf = { version = "*", features = ["macros", "unicase"] }
unicase = "*"
urlencoding = "*"

# Optional dependencies
quinn = { version = "*", features = ["rustls"], optional = true }

[features]
default = []
debugging = []
http3 = ["dep:quinn"]

[profile.release]
opt-level = 3
debug = true
codegen-units = 1
lto = true
