[package]
name = "servente"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
brotli = { version = "*", default-features = false, features = ["std"] }
flate2 = "*"
httpdate = "*"
lazy_static = "*"
rcgen = "*"
rstest = "*"
rustls = { version = "*", features = ["quic", "secret_extraction"] }
rustls-pemfile = "*"
stretto = { version = "*", features = ["async"] }
strum = "*"
strum_macros = "*"
tokio = { version = "*", features = ["full"] }
tokio-rustls = "*"
phf = { version = "*", features = ["macros", "unicase"] }
unicase = "*"
urlencoding = "*"


# Optional dependencies
scraper = { version = "*", optional = true }
notify = { version = "*", optional = true }
quinn = { version = "*", features = ["rustls"], optional = true }
ktls = { version = "*", optional = true }

[features]
default = ["analysis", "watch"]

analysis = ["dep:scraper"]
debugging = []
ktls = ["dep:ktls"]
http3 = ["dep:quinn"]

# Watch for changes in the filesystem
watch = ["dep:notify"]

[profile.release]
opt-level = 3
debug = true
codegen-units = 1
lto = true
