[package]
name = "servente_generator"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license.workspace = true
license-file = "../COPYING"

[dependencies]
regex = "*"

[features]
default = ["markdown"]
markdown = []
