[package]
name = "servente"
edition.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = "*"
futures = "*"
hashbrown = "*"
httpdate = "*"
itertools = "*"
lazy_static = "*"
rcgen = "*"
rstest = "*"
rustls = { version = "*", features = ["quic", "secret_extraction"] }
rustls-pemfile = "*"
strum = "*"
strum_macros = "*"
tokio = { version = "*", features = ["full"] }
tokio-rustls = "*"
phf = { version = "*", features = ["macros", "unicase"] }
unicase = "*"
urlencoding = "*"


# Optional dependencies
scraper = { version = "*", optional = true }
notify = { version = "*", optional = true }
quinn = { version = "*", features = ["rustls"], optional = true }
ktls = { version = "*", optional = true }

servente_generator = { version = "*", path = "../servente_generator", default-features = false }
servente_resources = { version = "*", path = "../servente_resources" }
servente_http = { version = "*", path = "../servente_http" }

[features]
default = ["analysis", "watch", "http2", "convert-markdown"]

analysis = ["dep:scraper"]
debugging = []
ktls = ["dep:ktls"]
http2 = []
http3 = ["dep:quinn"]

convert-markdown = ["servente_generator/markdown", "servente_resources/convert-markdown"]

# Watch for changes in the filesystem
watch = ["dep:notify"]
