name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CI_FEATURES: servente/analysis,servente/convert-markdown,servente/http2,servente/watch

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        profile: [dev, release]
        tls: ["rustls", "tls-boring"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/setup-nasm@v1
      if: ${{ matrix.tls == 'tls-boring' }}
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --locked --profile ${{ matrix.profile }} --no-default-features --features ${{ env.CI_FEATURES }} --features servente/${{ matrix.tls }}
    - name: Run tests
      run: cargo test --verbose --locked --profile ${{ matrix.profile }} --no-default-features --features ${{ env.CI_FEATURES }} --features servente/${{ matrix.tls }}
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
